import socket
server_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server_socket.bind((socket.gethostname(), 12345))
server_socket.listen(1)
print("Listening on port 12345...")
conn, addr = server_socket.accept()
print("Connection from", addr)
print("Client says:", conn.recv(1024).decode())
conn.send(b"Hello from server!")
conn.close()
